const express = require('express');
const dotenv = require('dotenv');
const cors = require('cors');
const connectDB = require('./config/db');
const scheduleAllocationJob = require('./jobs/allocationCronJob');
dotenv.config();
connectDB();
const app = express();
app.use(express.json());
app.use(cors());
app.use('/api/auth', require('./routes/authRoutes'));
app.use('/api/attendance', require('./routes/attendanceRoutes'));
app.use('/api/routes', require('./routes/routeRoutes'));
app.use('/api/buses', require('./routes/busRoutes'));
app.use('/api/allocation', require('./routes/allocationRoutes'));
app.use('/api/tickets', require('./routes/ticketRoutes'));
scheduleAllocationJob();
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));